#!/usr/bin/env python3
"""Compose the README matrix from outputs generated by generate.py."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps

from image_ops import normalize_depth_background


HERE = Path(__file__).resolve().parents[1]
LOGGER = logging.getLogger(__name__)


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        Path(
            "C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf"
        ),
        Path(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
            if bold
            else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
        ),
    ]
    for candidate in candidates:
        if candidate.is_file():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


def centered_x(
    draw: ImageDraw.ImageDraw, text: str, text_font, left: int, width: int
) -> float:
    box = draw.textbbox((0, 0), text, font=text_font)
    return left + (width - (box[2] - box[0])) / 2


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, default=HERE / "outputs" / "raw")
    parser.add_argument(
        "--output",
        type=Path,
        default=HERE / "outputs" / "character-control-matrix.webp",
    )
    args = parser.parse_args()

    manifest = json.loads((HERE / "demo.json").read_text(encoding="utf-8"))
    runs = {run["id"]: run for run in manifest["runs"]}
    width, height = 1740, 1510
    canvas = Image.new("RGB", (width, height), (247, 246, 243))
    draw = ImageDraw.Draw(canvas)
    title_font, regular, bold, small = (
        font(38, True),
        font(24),
        font(25, True),
        font(19),
    )

    draw.text(
        (42, 25),
        "Krea 2 Depth / Pose Control — real Forge outputs",
        font=title_font,
        fill=(25, 29, 35),
    )
    draw.text(
        (43, 73),
        "Three unique OpenPose inputs, one Depth input, four character interpretations",
        font=regular,
        fill=(82, 88, 96),
    )

    x0, cell, gap, header_y = 145, 296, 20, 120
    for index, column in enumerate(manifest["matrix"]["columns"]):
        left = x0 + index * (cell + gap)
        draw.text(
            (centered_x(draw, column.upper(), bold, left, cell), header_y),
            column.upper(),
            font=bold,
            fill=(35, 39, 47),
        )

    y0, row_height = 164, 322
    for row_index, row in enumerate(manifest["matrix"]["rows"]):
        y = y0 + row_index * row_height
        mode, label = row["label"].split(" / ", 1)
        pill = (63, 105, 177) if mode == "OPENPOSE" else (104, 83, 153)
        draw.rounded_rectangle((20, y + 12, 126, y + 47), radius=16, fill=pill)
        draw.text(
            (centered_x(draw, mode, small, 20, 106), y + 18),
            mode,
            font=small,
            fill="white",
        )
        draw.text(
            (centered_x(draw, label, bold, 20, 106), y + 62),
            label,
            font=bold,
            fill=(35, 39, 47),
        )

        source = manifest["sources"][row["source_id"]]
        paths = [HERE / source["file"]]
        for selected in row["outputs"]:
            run = runs[selected["run"]]
            if selected["index"] >= run["batch_size"]:
                raise RuntimeError(f"invalid selection for {run['id']}")
            paths.append(args.input_dir / f"{run['id']}-{selected['index']}.png")

        for column_index, path in enumerate(paths):
            if not path.is_file():
                raise FileNotFoundError(path)
            image = Image.open(path).convert("RGB")
            if row["source_id"] == "depth" and column_index > 0:
                character = manifest["matrix"].get("columns")[column_index]
                image = normalize_depth_background(image, character)
            fitted = ImageOps.contain(image, (cell, cell), Image.Resampling.LANCZOS)
            tile = Image.new("RGB", (cell, cell), "white")
            tile.paste(
                fitted, ((cell - fitted.width) // 2, (cell - fitted.height) // 2)
            )
            x = x0 + column_index * (cell + gap)
            canvas.paste(tile, (x, y))
            draw.rounded_rectangle(
                (x, y, x + cell - 1, y + cell - 1),
                radius=5,
                outline=(205, 207, 211),
                width=2,
            )

    draw.text(
        (42, 1474),
        "Pose strength 0.88  •  Depth strength 0.88–0.92  •  8 steps  •  Euler / Simple  •  CFG 1.0  •  768×768",
        font=small,
        fill=(88, 92, 99),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(args.output, "WEBP", quality=92, method=6)
    LOGGER.info("wrote %s (%dx%d)", args.output, width, height)


if __name__ == "__main__":
    main()
